### ISSUE TITLE
使用o1-mini模型的时候出现报错

### ISSUE THREAD

**Issue by jdassd** [NitroRCr/AIaW#1]
使用o1-mini模型的时候出现报错：
Unsupported value: 'messages[0].role' does not support 'system' with this model.
应该是没有指定为用户或助手的请求方式，但是界面上没看到在哪里修改它

**Comment by NitroRCr** [comment]
自定义提示词的role，这个功能目前没有，可以加。不过这个问题我却无法复现，我使用 o1-mini，可以添加系统提示且无报错
![image](https://github.com/user-attachments/assets/58d48fa9-f781-46c7-a87f-f856c34e51ce)
不知道是不是API的原因。我使用的中转 API 和 OpenRouter 测试的，请问你使用的是官方API吗？

**Comment by jdassd** [comment]
我使用的是几家中转 API 进行的测试，不知道是不是中转 API 的拦截报错，如果新建助手不修改任何配置，可以使用o1-mini进行对话，然后仅填写角色设定这一项其余不做修改，再次进行对话就不可以对话了

**Comment by jdassd** [comment]
我开通 OpenRouter 后进行测试，输入提示词可以也可以成功，应该是中转 API 的问题。

**Comment by NitroRCr** [comment]
现在可以自定义提示词role了
